version: "3.5"

services:

  api-service:
    build: api-service/
    image: api-service:latest
    ports:
      - "8080:8080"

  books-service:
    build: ./books-service/
    image: books-service:latest
    ports:
      - "8081"
